---
substitutions:
  api_key: yEr/yr9Q5YBrH6DsOFVjax5cIKuvAKqqv3VwsWMm4Yg=
  ota_key: super_secret_ota_key
  device_name: athom_wled
  friendly_name: Athom WLED
  wifi_ssid: iot_wifi
  wifi_pass: iot_secret_wifi_pass
  wifi_power_save: none

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platformio_options:
    # https://github.com/platformio/platform-espressif32/issues/622
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: arduino
    version: recommended

preferences:
  flash_write_interval: 5min

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  power_save_mode: ${wifi_power_save}
  output_power: 8.5dB

api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_key}

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: UART0

light:
  - platform: esp32_rmt_led_strip
    name: ${friendly_name} LEDs
    chipset: WS2812
    pin: GPIO10
    num_leds: 300
    rmt_channel: 0
    rgb_order: GRB
    effects:
      - addressable_rainbow:
          name: Rainbow

binary_sensor:
  - platform: gpio
    name: ${friendly_name} button
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
